language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t alfredmaboa -f Dockerfile.dev .

script:
    - docker run -e CI=true alfredmaboa npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    regioin: "us-east-2"
    app: "docker"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-497066619919"
    bucket_path: "Docker-React"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY